### ISSUE TITLE
Do not override configuration when reusing images

### ISSUE THREAD

**Issue by kokosing** [trinodb/docker-images#40]
Example, one image provides hadoop and so it contains core-site.xml, then that image is used as base for another image (with some additional feature like KRB) and then it overrides core-site.xml. This approach makes it very unclear what actually has changed between these images.

One idea to fix this is to use apply-site-xml-override.sh from https://github.com/prestosql/presto/pull/1958#discussion_r343593949

**Comment by findepi** [comment]
Migrated to https://github.com/trinodb/trino/issues/1978
